name: flutter_base_project
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  catcher: ^0.6.9
  device_preview: ^1.0.0
  version_tracker: ^2.1.1
  dio: ^4.0.4
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
  assets:
    - assets/languages/
    - assets/images/

flutter_native_splash:
  color: "#e1f5fe"
  image: assets/images/flutter_logo.png

  color_dark: "#042a49"
  image_dark: assets/images/flutter_logo_light.png

  web: false
  android: true
  ios: true

  fullscreen: true